from django.urls import path, re_path
from . import views, functions

urlpatterns = [
    path('', views.index),
    path('page1', views.page1),
    path('page2', views.page2),
    path('page3', views.page3),
    path('page4', views.page4),
    path('page5', views.page5),
    path('page6', views.page6),
    path('page7', views.page7),
    path('page8', views.page8),
    path('page9', views.page9),
    path('page10', views.page10),
    path('page11', views.page11),
    path('page12', views.page12),
    path('page13', views.page13),
    path('page14', views.page14),
    path('page15', views.page15),
    path('page16', views.page16),
    path('action_1', functions.action_1),
    path('action_2', functions.action_2),
    path('action_3', functions.action_3),
    path('action_4', functions.action_4),
    path('action_5', functions.action_5),
    path('action_6', functions.action_6),
    path('action_7', functions.action_7),
    path('action_8', functions.action_8),
    path('action_9', functions.action_9),
    path('action_10', functions.action_10),
    path('action_11', functions.action_11),
    path('action_12', functions.action_12),
    path('action_13', functions.action_13),
    path('action_14', functions.action_14),
    path('action_15', functions.action_15),
    path('action_16', functions.action_16),
]
